#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 30:00
#SBATCH -J QC_RNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user male6723@student.uu.se
#SBATCH --output=%x.%j.out

OUTPUT='/home/msl001/GenomeAnalysis/analyses/00_Quality-Control/RNA'
INPUT_PATH='/home/msl001/GenomeAnalysis/data/raw_data/RNA_reads/'

module load bioinfo-tools
module load FastQC

for i in "R7_A" "R7_B" "R7_C" "HP126_A" "HP126_B" "HP126_C" "DV3_A" "DV3_B" "DV3_C";
do 
    fastqc -o $OUTPUT --threads 2 "${INPUT_PATH}${i}_1.fastq.gz" "${INPUT_PATH}${i}_2.fastq.gz"
done