#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 15
#SBATCH -t 1:30:00
#SBATCH -J RNA_mapping
#SBATCH --mail-type=ALL
#SBATCH --mail-user male6723@student.uu.se
#SBATCH --output=%x.%j.out

OUTPUT='/home/msl001/GenomeAnalysis/data/mapped_data/RNA/'
ASSEMBLY_INPUT='/home/msl001/GenomeAnalysis/analyses/02_Assembly/'
TRIM_INPUT='/home/msl001/GenomeAnalysis/data/trimmed_data/RNA/'

module load bioinfo-tools
module load bwa
module load samtools

for index in "R7" "HP126" "DV3" ;
do
(
bwa index "${ASSEMBLY_INPUT}${i}/assembly.fasta"

bwa mem -t 5 "${ASSEMBLY_INPUT}${i}/assembly.fasta" \
"${TRIM_INPUT}${i}_A_1.P.trimmed.fastq.gz" \
"${TRIM_INPUT}${i}_A_2.P.trimmed.fastq.gz" \
> ${OUTPUT}${i}_A.sam

bwa mem -t 5 "${ASSEMBLY_INPUT}${i}/assembly.fasta" \
"${TRIM_INPUT}${i}_B_1.P.trimmed.fastq.gz" \
"${TRIM_INPUT}${i}_B_2.P.trimmed.fastq.gz" \
> ${OUTPUT}${i}_B.sam

bwa mem -t 5 "${ASSEMBLY_INPUT}${i}/assembly.fasta" \
"${TRIM_INPUT}${i}_C_1.P.trimmed.fastq.gz" \
"${TRIM_INPUT}${i}_C_2.P.trimmed.fastq.gz" \
> ${OUTPUT}${i}_C.sam
) &
done

wait