#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 9
#SBATCH -t 1:00:00
#SBATCH -J Read_counting
#SBATCH --mail-type=ALL
#SBATCH --mail-user male6723@student.uu.se
#SBATCH --output=%x.%j.output

module load bioinfo-tools
module load samtools
module load htseq


RNA_INPUT='/home/msl001/GenomeAnalysis/data/mapped_data/RNA/'
ANNO_INPUT='/home/msl001/GenomeAnalysis/analyses/04_Annotation/'
OUTPUT='/home/msl001/GenomeAnalysis/analyses/07_DE_analysis/'


for i in "R7" "HP126" "DV3";
do
(
htseq-count -f bam -r pos -a 0 --stranded=reverse -i ID -t CDS ${RNA_INPUT}${i}_A.bam ${ANNO_INPUT}R7/DNA_annotated_clean.gff > ${OUTPUT}${i}_A.txt &
htseq-count -f bam -r pos -a 0 --stranded=reverse -i ID -t CDS ${RNA_INPUT}${i}_B.bam ${ANNO_INPUT}R7/DNA_annotated_clean.gff > ${OUTPUT}${i}_B.txt &
htseq-count -f bam -r pos -a 0 --stranded=reverse -i ID -t CDS ${RNA_INPUT}${i}_C.bam ${ANNO_INPUT}R7/DNA_annotated_clean.gff > ${OUTPUT}${i}_C.txt
) &
done

wait