#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 15
#SBATCH -t 01:00:00
#SBATCH -J annotation
#SBATCH --mail-type=ALL
#SBATCH --mail-user male6723@student.uu.se
#SBATCH --output=%x.%j.out

INPUT='/home/msl001/GenomeAnalysis/data/mapped_data/DNA/'
OUTPUT='/home/msl001/GenomeAnalysis/analyses/04_Annotation/'

module load bioinfo-tools
module load prokka

for i in "R7" "HP126" "DV3" ;
do
(
prokka "${INPUT}${i}_pilon.fasta" \
--outdir "${OUTPUT}${i}" --prefix DNA_annotated \
--cpus 5 --force
) &
done

wait