#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:15:00
#SBATCH -J QC_DNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user male6723@student.uu.se
#SBATCH --output=%x.%j.out

OUTPUT='/home/msl001/GenomeAnalysis/analyses/00_Quality-Control/DNA'
INPUT_PATH='/home/msl001/GenomeAnalysis/data/raw_data/DNA_reads/short_reads/'

module load bioinfo-tools
module load FastQC

for i in {65,71,80};
do 
    fastqc -o $OUTPUT --threads 2 "${INPUT_PATH}SRR244130${i}_1.fastq.gz" "${INPUT_PATH}SRR244130${i}_2.fastq.gz"
done