#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 4:00:00
#SBATCH -J DNA_trimming_long
#SBATCH --mail-type=ALL
#SBATCH --mail-user male6723@student.uu.se
#SBATCH --output=%x.%j.out

OUTPUT_PATH='/home/msl001/GenomeAnalysis/data/trimmed_data/long_DNA/'
INPUT_PATH='/home/msl001/GenomeAnalysis/data/raw_data/DNA_reads/'

module load bioinfo-tools
module load Porechop

for i in "R7" "HP126" "DV3" ;
do
porechop -i "${INPUT_PATH}${i}.fastq.gz" -o "${OUTPUT_path}${i}.trimmed.fastq.gz" --threads 2
done
